#ifndef AVIDLIB_CONTAINERS_MDLV10_MDLFILE_H
#define AVIDLIB_CONTAINERS_MDLV10_MDLFILE_H

#include "AVIDLib_Containers/LibExport.h"

API_AVIDLIB_CONTAINERS void ALC_MDLv10_Test();

#endif // AVIDLIB_CONTAINERS_MDLV10_MDLFILE_H
