#ifndef AVIDLIB_TOOLS_MDLVIEWER_OPENMDLFILEDIALOGUE_H
#define AVIDLIB_TOOLS_MDLVIEWER_OPENMDLFILEDIALOGUE_H

namespace OpenMDLFileDialogue
{
	void Draw();
	void Poll();
	void Open();
}

#endif // AVIDLIB_TOOLS_MDLVIEWER_OPENMDLFILEDIALOGUE_H
