#ifndef AVIDLIB_TOOLS_MDLVIEWER_TESTFRAMEBUFFERRENDERER_H
#define AVIDLIB_TOOLS_MDLVIEWER_TESTFRAMEBUFFERRENDERER_H

namespace TestFramebufferRenderer
{
	void Init();
	void Draw();
	void Cleanup();
}

#endif // AVIDLIB_TOOLS_MDLVIEWER_TESTFRAMEBUFFERRENDERER_H
