name: continuous-integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build on Ubuntu Latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [ "Debug", "Release", "MinSizeRel", "RelWithDebInfo" ]
        shared-libs: [ "YES", "NO" ]

    steps:
    - uses: actions/checkout@v2

    - name: Create build dir
      run: |
        mkdir build

    - name: Configure (config = ${{matrix.config}}, shared libs = ${{matrix.shared-libs}})
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{matrix.config}} -DBUILD_SHARED_LIBS=${{matrix.shared-libs}} -DCONTAINERS_ALL=YES ..

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{matrix.config}}
