name: continuous-integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This job builds all content in a handful of configurations,
  # and leaves the more specific build options at their defaults.
  build-linux-nonspecific:
    name: Nonspecific build on Ubuntu Latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [ "Debug", "Release", "MinSizeRel", "RelWithDebInfo" ]
        shared-libs: [ "YES", "NO" ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev

    - name: Create build dir
      run: |
        mkdir build

    - name: Configure (config = ${{matrix.config}}, shared libs = ${{matrix.shared-libs}})
      run: |
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=${{matrix.config}} \
          -DBUILD_SHARED_LIBS=${{matrix.shared-libs}} \
          -DCONTAINERS_ALL=YES \
          -DBUILD_TOOLS=YES \
          -DTOOLS_ALL=YES \
          ..

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{matrix.config}}
